apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc
  namespace: miroit-access
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName:  content-api-file-pv