apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.service.name }}-file-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.filePath }}