apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-pvc
  namespace: nexus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
{{/*  storageClassName: {{ .Values.service.name }}-pv*/}}
  volumeMode: Filesystem