apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.service.name }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/root/nexus-data"