apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-pvc
  namespace: miroit-access
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName:  miroit-nexus-pv