apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.service.name }}-pv
  labels:
    type: local
spec:
{{/*  storageClassName: {{ .Values.service.name }}-pv*/}}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/nexus"